name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12 UTC everyday
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: waka time metric
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
